=== networkoptix/nx_open/mediaserver_core/static-resources/plugins/nx_metadata_plugin_manifest.schema.json
{
    "$schema": "http://json-schema.org/draft-04/schema#",
    "title": "Network Optix metadata plugin manifest",
    "type": "object",
    "properties": {
        "acceptedDataTypes": {
            "type": "array",
            "description": "Types of data that can be accepted by plugin",
            "items": {
                "type": "string",
                "enum":[
                    "compressedVideo",
                    "compressedAudio",
                    "decompressedVideo",
                    "decompressedAudio",
                    "metadata"]
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "supportedCodecs": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["video/avc", "video/hevc", "image/jpeg", "some", "audio", "codecs"]
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "supportedHandleTypes": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["none, glTexture", "xvShmImage", "coreImage", "qPixmap", "eglImage"]
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "supportedPixelFormats": {
            "type": "array",
            "items": {
                "type": "string",
                "enum": ["YUV_420", "YUV_442", "YUV_444", "NV_12", "RGB", "RGBA", "ABGR", "BGR"]
            },
            "minItems": 1,
            "uniqueItems": true
        },
        "outputEventTypes": {
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "kindName": {
                        "type": "string"
                    },
                    "localization":{
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "locale": {
                                    "type": "string"
                                },
                                "kindName": {
                                    "type": "string"
                                }
                            },
                            "required": ["locale", "kindName"]
                        },
                        "minItems": 1,
                        "uniqueItems": true
                    }
                },
                "required": ["kindName", "localization"]
            },
            "minItems": 1,
            "uniqueItems": true
        }
    }
}

=== networkoptix/nx_open/mediaserver_core/static-resources/plugins/manifest_example.json
{
    "acceptedDataTypes": ["compressedVideo", "decompressedVideo"],
    "supportedCodecs": ["video/avc"],
    "supportedHandleTypes": ["eglImage"],
    "supportedPixelFormats": ["YUV_444"],
    "outputEventTypes": [
        {
            "kindName": "Line crossing",
            "localization": [
                {"locale": "ru-RU", "kindName": "Пересечение линии"},
                {"locale": "uk-UA", "kindName": "Перетин лiнiї"}
            ]
        },
        {
            "kindName": "Object in the area",
            "localization": [
                {"locale": "ru-RU", "kindName": "Объект внутри области"},
                {"locale": "ru-RU", "kindName": "Об'єкт всередині області"}
            ]
        }
    ]
}
